### ISSUE TITLE
建议收录的一些信息

### ISSUE THREAD

**Issue by PueMake** [Skr1llix/TZG-LTCat-s-war#2]
存档了TZG的高材生的一些账号，建议加速收录

微博：https://weibo.com/u/3211723945
V2EX：https://archive.vn/9wu0D
知乎：https://archive.vn/paqa2
萌娘：https://archive.vn/qrnnr
B站：https://archive.vn/26hFK
少数派：https://archive.vn/gKHcQ
MCBBS：https://archive.vn/LiBBj
阿里云：https://archive.vn/jbpH8
BeatStage：https://archive.vn/pPVeJ

**Comment by Skr1llix** [comment]
👌

**Comment by PueMake** [comment]
> 👌

部分链接已失效，提交了一个PR，做了一点点微小的贡献。
